version: '3'
services:
  web:
    build: ./
    ports:
      - "81:80"
    depends_on:
      - db
    expose:
      - 9010
    volumes:
      - ./:/var/www/html/
      - ./config/php.ini:/usr/local/etc/php/php.ini
      - ./config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - chamla_poo_network

  db:
    image: mysql
    ports:
      - "3311:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chamla_poo_db
      MYSQL_USER: 123456
      MYSQL_PASSWORD: badr
    volumes:
      - "./db:/var/lib/mysql"
    networks:
      - chamla_poo_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8081:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - chamla_poo_network

networks:
  chamla_poo_network:
    driver: bridge
